server:
  tomcat:
    threads:
      max: '10'
  port: '8080'
spring:
  application:
    name: team-app
  ##  server.tomcat.threads.max=10 : HTTP (Tomcat)will only accept 10 -> by default => 200 ##
  ## Enabling Java21 - Virtual Threads ##
  threads:
    virtual:
      enabled: 'true'